[versions]
# libraries
mcmsgdef = "1.0.0"
paper = "1.21.10-R0.1-SNAPSHOT"

# gradle plugins
run-task = "3.0.2"
gradle-plugins = "1.6.1"

[libraries]
mcmsgdef = { module = "dev.siroshun.mcmsgdef:mcmsgdef", version.ref = "mcmsgdef" }
platform-paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

[plugins]

run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
bundler = { id = "dev.siroshun.gradle.plugins.bundler", version.ref = "gradle-plugins" }
jcommon = { id = "dev.siroshun.gradle.plugins.jcommon", version.ref = "gradle-plugins" }
